[build]
builder = "nixpacks"

[deploy]
startCommand = "pip install poetry==1.8.2 && poetry install && chmod +x ./letta/server/startup.sh && ./letta/server/startup.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
healthcheckInterval = 30
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8283"
HOST = "0.0.0.0"
LETTA_PG_URI = "${DATABASE_URL}"
LETTA_LLM_ENDPOINT = "https://generativelanguage.googleapis.com"
LETTA_LLM_ENDPOINT_TYPE = "google_ai"
LETTA_LLM_MODEL = "gemini-2.0-flash"
LETTA_EMBEDDING_ENDPOINT = "https://generativelanguage.googleapis.com"
LETTA_EMBEDDING_ENDPOINT_TYPE = "google_ai"
LETTA_EMBEDDING_MODEL = "embedding-001"
SECURE = "true"
