[build]
builder = "nixpacks"

[deploy]
startCommand = "pip install poetry==1.8.2 && poetry install && poetry run python -m letta.server --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
PORT = "8283"
HOST = "0.0.0.0"
POSTGRES_DB = "letta"
LETTA_LLM_ENDPOINT = "https://generativelanguage.googleapis.com"
LETTA_LLM_ENDPOINT_TYPE = "google_ai"
LETTA_LLM_MODEL = "gemini-2.0-flash"
LETTA_EMBEDDING_ENDPOINT = "https://generativelanguage.googleapis.com"
LETTA_EMBEDDING_ENDPOINT_TYPE = "google_ai"
LETTA_EMBEDDING_MODEL = "embedding-001"
SECURE = "true"
